insert into biblioteca.book(title , author , year_published , isbn , available) values ('Classical Mythology','Mark P. O. Morford',2002 ,'195153448',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Clara Callan','Richard Bruce Wright',2001 ,'2005018',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Decision in Normandy','Carlo D''Este',1991 ,'60973129',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It','Gina Bari Kolata',1999 ,'374157065',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Mummies of Urumchi','E. J. W. Barber',1999 ,'393045218',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Kitchen God''s Wife','Amy Tan',1991 ,'399135782',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('What If?: The World''s Foremost Military Historians Imagine What Might Have Been','Robert Cowley',2000 ,'425176428',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('PLEADING GUILTY','Scott Turow',1993 ,'671870432',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Under the Black Flag: The Romance and the Reality of Life Among the Pirates','David Cordingly',1996 ,'679425608',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Where You''ll Find Me: And Other Stories','Ann Beattie',2002 ,'074322678X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Nights Below Station Street','David Adams Richards',1988 ,'771074670',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Hitler''s Secret Bankers: The Myth of Swiss Neutrality During the Holocaust','Adam Lebor',2000 ,'080652121X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Middle Stories','Sheila Heti',2004 ,'887841740',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Jane Doe','R. J. Kaiser',1999 ,'1552041778',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('A Second Chicken Soup for the Woman''s Soul (Chicken Soup for the Soul Series)','Jack Canfield',1998 ,'1558746218',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Witchfinder (Amos Walker Mystery Series)','Loren D. Estleman',1998 ,'1567407781',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('More Cunning Than Man: A Social History of Rats and Man','Robert Hendrickson',1999 ,'1575663937',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Goodbye to the Buttermilk Sky','Julia Oliver',1994 ,'1881320189',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Testament','John Grisham',1999 ,'440234743',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Beloved (Plume Contemporary Fiction)','Toni Morrison',1994 ,'452264464',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Our Dumb Century: The Onion Presents 100 Years of Headlines from America''s Finest News Source','The Onion',1999 ,'609804618',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('New Vegetarian: Bold and Beautiful Recipes for Every Occasion','Celia Brooks Brown',2001 ,'1841721522',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('If I''d Known Then What I Know Now: Why Not Learn from the Mistakes of Others? : You Can''t Afford to Make Them All Yourself','J. R. Parrish',2003 ,'1879384493',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Mary-Kate & Ashley Switching Goals (Mary-Kate and Ashley Starring in)','Mary-Kate & Ashley Olsen',2000 ,'61076031',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tell Me This Isn''t Happening','Robynn Clairday',1999 ,'439095026',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Flood : Mississippi 1927','Kathleen Duey',1998 ,'689821166',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Wild Animus','Rich Shapero',2004 ,'971880107',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Airframe','Michael Crichton',1997 ,'345402871',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Timeline','MICHAEL CRICHTON',2000 ,'345417623',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('OUT OF THE SILENT PLANET','C.S. Lewis',1996 ,'684823802',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Prague : A Novel','ARTHUR PHILLIPS',2003 ,'375759778',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Chocolate Jesus','Stephan Jaramillo',1998 ,'425163091',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Wie Barney es sieht.','Mordecai Richler',2002 ,'3404921038',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Der Fluch der Kaiserin. Ein Richter- Di- Roman.','Eleanor Cooney',2001 ,'3442353866',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Sturmzeit. Roman.','Charlotte Link',1991 ,'3442410665',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tage der Unschuld.','Richard North Patterson',2000 ,'3442446937',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Lying Awake','Mark Salzman',2000 ,'375406328',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('To Kill a Mockingbird','Harper Lee',1988 ,'446310786',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Seabiscuit: An American Legend','LAURA HILLENBRAND',2002 ,'449005615',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pigs in Heaven','Barbara Kingsolver',1993 ,'60168013',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Miss Zukas and the Raven''s Dance','Jo Dereske',1996 ,'038078243X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pride and Prejudice','Jane Austen',1983 ,'055321215X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Therapeutic Touch: How to Use Your Hands to Help or to Heal','Dolores Krieger',1979 ,'067176537X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Downtown','Anne Rivers Siddons',1995 ,'61099686',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Icebound','Dean R. Koontz',2000 ,'553582909',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('I''ll Be Seeing You','Mary Higgins Clark',1994 ,'671888587',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('From the Corner of His Eye','Dean Koontz',2001 ,'553582747',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Isle of Dogs','Patricia Cornwell',2002 ,'425182908',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Purity in Death','J.D. Robb',2002 ,'042518630X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('This Year It Will Be Different: And Other Stories','Maeve Binchy',1997 ,'440223571',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Proxies','Laura J. Mixon',1999 ,'812523873',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Left Behind: A Novel of the Earth''s Last Days (Left Behind #1)','Tim Lahaye',2000 ,'842342702',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Street Lawyer','JOHN GRISHAM',1999 ,'440225701',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Love','',0000 ,'60914068',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('All the King''s Men','Robert Penn Warren',1982 ,'156047624',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pacific Northwest','Hans Johannes Hoefer',1985 ,'245542957',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('A Soldier of the Great War','Mark Helprin',1992 ,'380715899',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Getting Well Again','O. Carol Simonton Md',1992 ,'553280333',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Northwest Wines and Wineries','Chuck Hill',1993 ,'961769947',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('An Atmosphere of Eternity: Stories of India','David Iglehart',2002 ,'964778319',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('LONESOME DOVE','Larry McMurtry',1986 ,'671623249',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Shabanu: Daughter of the Wind (Border Trilogy)','SUZANNE FISHER STAPLES',1991 ,'679810307',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Haveli (Laurel Leaf Books)','SUZANNE FISHER STAPLES',1995 ,'679865691',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Lieux dits','Michel Tournier',2002 ,'2070423204',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Dragons of Eden: Speculations on the Evolution of Human Intelligence','Carl Sagan',1978 ,'345260317',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The yawning heights','Aleksandr Zinoviev',1980 ,'394743741',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Breathing Lessons','Anne Tyler',1994 ,'042511774X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Joy Luck Club','Amy Tan',1994 ,'804106304',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Heart of Darkness (Wordsworth Collection)','Joseph Conrad',1998 ,'1853262404',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Angel Is Near','Deepak Chopra',2000 ,'312970242',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tess of the D''Urbervilles (Wordsworth Classics)','Thomas Hardy',1997 ,'1853260053',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Adventures of Drew and Ellie: The Magical Dress','Charles Noland',2003 ,'1414035004',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Accidental Virgin','Valerie Frankel',2003 ,'60938412',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Tao of Pooh','Benjamin Hoff',1983 ,'140067477',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Seabiscuit','LAURA HILLENBRAND',2003 ,'345465083',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Prince','Niccolo Machiavelli',1952 ,'451625889',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Life''s Little Instruction Book (Life''s Little Instruction Books (Paperback))','H. Jackson Brown',1991 ,'1558531025',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Starship Troopers','Robert A. Heinlein',1987 ,'441783589',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Ruby in the Smoke (Sally Lockhart Trilogy','',0000 ,'394895894',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Black Beauty (Illustrated Classics)','Anna Sewell',1995 ,'1569871213',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Anil''s Ghost','MICHAEL ONDAATJE',2000 ,'375410538',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Prescription for Terror','Sandra Levy Ceren',1999 ,'966986105',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Modern Manners: An Etiquette Book for Rude People','P.J. O''Rourke',1990 ,'087113375X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Turning Thirty','Mike Gayle',2000 ,'340767936',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Decipher','Stel Pavlou',2002 ,'743403843',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('My First Cousin Once Removed: Money','',0000 ,'60930365',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Standing Firm: A Vice-Presidential Memoir','Dan Quayle',1994 ,'60177586',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Team Bush : Leadership Lessons from the Bush White House','Donald F. Kettl',2003 ,'71416331',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Right Man : The Surprise Presidency of George W. Bush','DAVID FRUM',2003 ,'375509038',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Daybreakers Louis Lamour Collection','Louis Lamour',1981 ,'553062042',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Catcher in the Rye','J.D. Salinger',1991 ,'316769487',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('El Senor De Los Anillos: LA Comunidad Del Anillo (Lord of the Rings (Spanish))','J. R. R. Tolkien',2001 ,'8445071408',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('El Senor De Los Anillos: Las DOS Torres (Lord of the Rings (Paperback))','J. R. R. Tolkien',2001 ,'8445071769',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('El Senor De Los Anillos: El Retorno Del Rey (Tolkien','',0000 ,'8445071777',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Midnight in the Garden of Good and Evil: A Savannah Story','John Berendt',1994 ,'679429220',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pretend You Don''t See Her','Mary Higgins Clark',1998 ,'671867156',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Fast Women','Jennifer Crusie',2001 ,'312252617',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Female Intelligence','Jane Heller',2001 ,'312261594',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pasquale''s Nose: Idle Days in an Italian Town','Michael Rips',2002 ,'316748641',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Gospel of Judas: A Novel','Simon Mawer',2002 ,'316973742',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Prize Stories','',0000 ,'385235941',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Rich Dad','',0000 ,'446677450',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Pillars of the Earth','Ken Follett',1996 ,'451166892',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('McDonald''s: Behind the Arches','John F. Love',1995 ,'553347594',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Creating Wealth : Retire in Ten Years Using Allen''s Seven Principles of Wealth!','Robert G. Allen',1986 ,'671621009',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Corelli''s Mandolin : A Novel','LOUIS DE BERNIERES',1995 ,'067976397X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Love','',0000 ,'684822733',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Five People You Meet in Heaven','Mitch Albom',2003 ,'786868716',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tu Nombre Escrito En El Agua (La Sonrisa Vertical)','Irene Gonzalez Frei',2002 ,'8472238822',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Relics (Star Trek: The Next Generation)','Michael Jan Friedman',1992 ,'671864769',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Bless The Beasts And Children : Bless The Beasts And Children','Glendon Swarthout',1995 ,'671521519',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Touch of Your Shadow','',0000 ,'440222303',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Blood Oath','David Morrell',1994 ,'312953453',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Alibi','Sandra Brown',2000 ,'446608653',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Beach House','James Patterson',2003 ,'446612545',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('A Kiss Remembered','Sandra Brown',2003 ,'446612618',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Short Forever','Stuart Woods',2003 ,'451208080',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Dead Aim','IRIS JOHANSEN',2004 ,'553584383',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Angels & Demons','Dan Brown',2001 ,'671027360',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Deal','Joe Hutsko',2000 ,'812575954',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('All He Ever Wanted: A Novel','Anita Shreve',2004 ,'316735736',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Every Breath You Take : A True Story of Obsession','',000 ,'743439740',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('If I Ever Get Back to Georgia','',0000 ,'345372700',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Mosquito Coast','Paul Theroux',1990 ,'380619458',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('If Love Were Oil','',0000 ,'446325805',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Goodbye','',0000 ,'451406923',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Girl Who Loved Tom Gordon','Stephen King',2000 ,'671042858',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Bringing Down the House: The Inside Story of Six M.I.T. Students Who Took Vegas for Millions','Ben Mezrich',2003 ,'743249992',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Oneprince (The Redaemian Chronicles','',0000 ,'840734530',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Sum of All Fears','Tom Clancy',2002 ,'425184226',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Care Packages : Letters to Christopher Reeve from Strangers and Other Friends','DANA REEVE',1999 ,'375500766',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('O Deus Das Pequenas Coisas','Roy',1998 ,'9724119378',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Lady in Green/Minor Indiscretions (Signet Regency Romance)','Barbara Metzger',2002 ,'451205197',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('One Hundred Years of Solitude','Gabriel Garcia Marquez',1998 ,'60929790',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Little Altars Everywhere: A Novel','Rebecca Wells',1996 ,'60976845',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Coyote Waits (Joe Leaphorn/Jim Chee Novels)','Tony Hillerman',1992 ,'61099325',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Before I Say Good-Bye','Mary Higgins Clark',2001 ,'671004573',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Slow Waltz in Cedar Bend','Robert James Waller',1994 ,'446601640',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Twenty Minute Retreats: Revive Your Spirits in Just Minutes a Day (A Pan Self-discovery Title)','Rachel Harris',2001 ,'330484516',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Atonement : A Novel','IAN MCEWAN',2003 ,'038572179X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Next: The Future Just Happened','Michael Lewis',2001 ,'393020371',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Angelic Darkness','Richard Zimler',1999 ,'1900850303',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Soulbane Stratagem','Norman Jetmundsen',2000 ,'1903019699',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Gangster','Lorenzo Carcaterra',2002 ,'345425294',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Hush','Anne Frasier',2002 ,'451410319',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Whisper of Evil (Hooper','',0000 ,'553583468',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Temor y Temblor','Soren Kierkegaard',2001 ,'8420639133',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Estudios sobre el amor','Jose Ortega Y Gaset',2001 ,'8476409419',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Rebecca','Daphne Du Maurier',1994 ,'380778556',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Scarlet Letter','Nathaniel Hawthorne',1993 ,'451525221',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Keep It Simple: And Get More Out of Life','Nick Page',1999 ,'2740230',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Diary of a Mad Mom-To-Be','Laura Wolf',2003 ,'385336772',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Locked in Time (Laurel Leaf Books)','LOIS DUNCAN',1986 ,'440949424',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Contact','Susan Grant',2002 ,'505524996',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Brimstone Wedding','Barbara Vine',1997 ,'140252800',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Catswold Portal','Shirley Rousseau Murphy',1993 ,'451452755',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Through Wolf''s Eyes (Wolf)','Jane Lindskold',2002 ,'812575482',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Puerto Vallarta Squeeze','Robert James Waller',1995 ,'044651747X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tree Grows In Brooklyn','Betty Smith',1988 ,'60801263',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Cybill Disobedience: How I Survived Beauty Pageants','',0000 ,'61030147',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Snow Angels','Stewart O''Nan',1995 ,'140250964',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Wish You Well','David Baldacci',2000 ,'446527165',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Hitchhiker''s Guide to the Galaxy','Douglas Adams',1982 ,'671461494',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Crow Lake (Today Show Book Club #7)','Mary Lawson',2003 ,'385337639',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('My Antonia','Willa Cather',1995 ,'039575514X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pen Pals','Olivia Goldsmith',2002 ,'451206673',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Bridget Jones''s Diary','Helen Fielding',1997 ,'330332775',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pride and Prejudice (Dover Thrift Editions)','Jane Austen',1995 ,'486284735',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('EYE ON CRIME: HARDY BOYS #153','Franklin W. Dixon',1998 ,'671021745',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Skin And Bones','Franklin W. Dixon',2000 ,'671047612',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('LAW OF THE JUNGLE (HARDY BOYS CASE FILE 105) : LAW OF THE JUNGLE (Hardy Boys','',0000 ,'671504282',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Cat Who Came to Breakfast (Cat Who... (Hardcover))','Lilian Jackson Braun',1994 ,'399138684',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('If Singleness Is a Gift','',0000 ,'785263292',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Always Daddy''s Girl: Understanding Your Father''s Impact on Who You Are','H. Norman Wright',1989 ,'830714014',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Night Mare (Xanth Novels (Paperback))','Piers Anthony',1990 ,'345354931',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Martian Chronicles','RAY BRADBURY',1984 ,'553278223',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Kabale Und Liebe','Schiller',0 ,'3150000335',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Der illustrierte Mann. ErzÃ?Â¤hlungen.','Ray Bradbury',2002 ,'3257203659',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Der KÃ?Â¶nig in Gelb.','Raymond Chandler',1980 ,'3257207522',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Fahrenheit 451','Ray Bradbury',1994 ,'3257208626',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Mars- Chroniken. Roman in ErzÃ?Â¤hlungen.','Ray Bradbury',1981 ,'3257208634',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Das BÃ?Â¶se kommt auf leisen Sohlen.','Ray Bradbury',2003 ,'3257208669',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('LÃ?Â¶wenzahnwein. Roman.','Ray Bradbury',1999 ,'3257210450',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Das Kind von morgen. ErzÃ?Â¤hlungen.','Ray Bradbury',2000 ,'3257212054',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Mechanismen der Freude. ErzÃ?Â¤hlungen.','Ray Bradbury',2000 ,'3257212429',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Familientreffen. ErzÃ?Â¤hlungen.','Ray Bradbury',2000 ,'3257214154',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Der Tod kommt schnell in Mexico. ErzÃ?Â¤hlungen.','Ray Bradbury',1988 ,'3257216416',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Veronika Deschliesst Zu Sterben / Vernika Decides to Die','Paolo Coelho',2002 ,'3257233051',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Liebe in Den Zelten','Gabriel Garcia Marquez',0 ,'342311360X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Klone der Joanna May. Roman.','Fay Weldon',1993 ,'3423116714',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Ist mein Hintern wirklich so dick? Tagebuch einer empfindsamen Frau.','Arabella Weir',1998 ,'3423241489',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Haifischfrauen.','Kiana Davenport',1996 ,'3426605686',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Cappuccino- Jahre. Aus dem Tagebuch des Adrian Mole.','Sue Townsend',2002 ,'3453212150',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Schwarzer Tee mit drei StÃ¼ck Zucker','Renan Demirkan',1991 ,'3462021095',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('QuerschÃ?Â¼sse - Downsize This!','Michael Moore',2003 ,'3492045642',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Die Korrekturen.','Jonathan Franzen',2002 ,'3498020862',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Neun ErzÃ?Â¤hlungen.','Jerome D. Salinger',1968 ,'3499110695',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Hebt den Dachbalken hoch','',0000 ,'3499151502',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Ulysses (Ã?Â?bersetzg. WollschlÃ?Â¤ger). ( Neue Folge','',0000 ,'3518111000',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Eine ganz normale AffÃ?Â¤re.','Joanna Trollope',2002 ,'3548254268',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Das Intimleben des Adrian Mole','',0000 ,'3570300099',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Das Buch der lÃ?Â¤cherlichen Liebe.','Milan Kundera',2000 ,'3596292646',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The God of Small Things','Arundhati Roy',1998 ,'60977493',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The James Dean Affair: A Neil Gulliver & Stevie Marriner Novel','Robert S. Levinson',2000 ,'312872682',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Big Bad Wolf: A Novel','James Patterson',2003 ,'316602906',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Four Blind Mice','James Patterson',2002 ,'316693006',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Private Screening','Richard North Patterson',1994 ,'345311396',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Congo','Michael Crichton',1995 ,'345378490',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Protect and Defend','Richard North Patterson',2001 ,'345404793',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Tall Pine Polka','Lorna Landvik',1999 ,'345433173',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Memoirs of a Geisha','Arthur Golden',1997 ,'375400117',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Plainsong (Vintage Contemporaries)','KENT HARUF',2000 ,'375705856',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Body of Evidence (Kay Scarpetta Mysteries (Paperback))','Patricia D. Cornwell',1992 ,'380717018',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('All That Remains (Kay Scarpetta Mysteries (Paperback))','Patricia D. Cornwell',1993 ,'380718332',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Case of the Lost Look-Alike (An Avon Camelot Book)','Carol J. Farley',1988 ,'380754509',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Petals on the River','Kathleen E. Woodiwiss',1997 ,'038076654X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Elusive Flame','Kathleen E. Woodiwiss',1999 ,'380807866',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Legacy of Silence','Belva Plain',1998 ,'385316895',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Brethren','JOHN GRISHAM',2000 ,'385497466',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The King of Torts','John Grisham',2003 ,'385508042',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Curious Incident of the Dog in the Night-Time : A Novel','MARK HADDON',2003 ,'385509456',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Bleachers','John Grisham',2003 ,'385511612',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Sisterhood of the Traveling Pants','ANN BRASHARES',2003 ,'385730586',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Only Love (Magical Love)','Erich Segal',1998 ,'425164403',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('All or Nothing (Wheeler Large Print Books)','Elizabeth Adler',2000 ,'440234964',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Roses Are Red (Alex Cross Novels)','James Patterson',2001 ,'446605484',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Rescue','Nicholas Sparks',2001 ,'446610399',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Manhattan Hunt Club','JOHN SAUL',2002 ,'449006522',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Patty Jane''s House of Curl (Ballantine Reader''s Circle)','LORNA LANDVIK',1996 ,'449911004',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Pet Sematary','Stephen King',1994 ,'451162072',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Silent Snow','Steve Thayer',2000 ,'451186648',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Girl with a Pearl Earring','Tracy Chevalier',2001 ,'452282152',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Summer of Storms','Judith Kelman',2002 ,'051513290X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Patient','Michael Palmer',2001 ,'553580388',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Demona''s Revenge (Gargoyles','',0000 ,'590598848',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Clifford''s Sports Day','Norman Bridwell',1996 ,'590629719',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Postmortem (Kay Scarpetta Mysteries (Paperback))','Patricia Cornwell',1998 ,'671023616',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Deception Point','Dan Brown',2002 ,'671027387',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Tis : A Memoir','Frank McCourt',1999 ,'684848783',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Angels & Demons','Dan Brown',2003 ,'743486226',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('A Monk Swimming','Malachy McCourt',1998 ,'786863986',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Crazy Horse','Mari Sandoz',1961 ,'803251718',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Silent Cry (William Monk Novels (Paperback))','Anne Perry',1998 ,'804117934',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('The Kalahari Typing School for Men (No. 1 Ladies''Detective Agency)','ALEXANDER MCCALL SMITH',2004 ,'140003180X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Chicken Soup for the Soul (Chicken Soup for the Soul)','Jack Canfield',1993 ,'155874262X',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Wicked: The Life and Times of the Wicked Witch of the West','Gregory Maguire',1996 ,'60987103',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Life of Pi','Yann Martel',2002 ,'151008116',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('A Judgement in Stone','Ruth Rendell',2000 ,'375704965',true);
insert into biblioteca.book(title , author , year_published , isbn , available) values ('Lies and the Lying Liars Who Tell Them: A Fair and Balanced Look at the Right','Al Franken',2003 ,'525947647',true);
