insert into biblioteca.customer(name,library_number,password,email,phone) values('Benita K','sbq-u4rs','pass','benita@gmail.com','4811304523');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Charumathi Manoharan','erf-oq8v','pass','charu@gmail.com','9770608410');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Geetika Chauhan','o6o-4n8c','pass','geetika@gmail.com','4317557850');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Indira Raghavan','1zt-ku9k','pass','indira@gmail.com','7708622611');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Janani T','b1x-yw7f','pass','janani@gmail.com','6243692078');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Kalpana Balakrishnan','5j3-5zvq','pass','kalpana@gmail.com','4727913696');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Kavitha K','3qf-6p3f','pass','kavitha@gmail.com','6382426565');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Malini S','nvv-6nkg','pass','malini@gmail.com','1811980012');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Mona Bansal','2wo-pc4n','pass','mona@gmail.com','502724745');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Neeti Patni','pmj-cume','pass','neeti@gmail.com','156642246');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Neha Mehak','dn2-fkb0','pass','neha@gmail.com','2243771666');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Padmavathi Gangasani','jdc-aarq','pass','padma@gmail.com','3916181919');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Priyanka Dayama','fq5-nvep','pass','priyanka@gmail.com','7174342734');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Rajatha U','tdl-2w74','pass','rajatha@gmail.com','162546509');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Ramya A R','33a-ld4v','pass','ramyaa@gmail.com','6498494358');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Ramya Ganesan','aks-tc17','pass','ramyag@gmail.com','4522308489');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Rathipriya Singaram','jmt-4i5p','pass','rathipriya@gmail.com','2527444490');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Rehana Syed','uqv-7gjx','pass','rehana@gmail.com','6557320969');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Sakthe Karthika       ','c91-x3uo','pass','sakthe@gmail.com','6975387247');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Sangeetha S','7f3-w10o','pass','sangeetha@gmail.com','8716642802');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Seethalakshmi M','xbb-ii75','pass','seetha@gmail.com','5548321486');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Sharanya Gopalakrishnan','jr9-aw63','pass','sharanya@gmail.com','9361514174');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Sneha S','nbm-rvk9','pass','sneha@gmail.com','2262948920');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Sowmya S B','cjz-7lv4','pass','sowmya@gmail.com','3649421726');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Vidhya M','pfy-u0af','pass','vidhya@gmail.com','3680759519');
insert into biblioteca.customer(name,library_number,password,email,phone) values('Vinay Yepuri','p5i-lhj8','pass','vinay@gmail.com','1176294913');